[project]
name = "py-videocore6"
description = "A Python library for GPGPU programming on Raspberry Pi 4"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "ioctl-opt>=1.3",
    "numpy>=2.3.1",
]
dynamic = ["version"]

[build-system]
requires = ["setuptools", "setuptools_scm"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools_scm]
version_file = "src/_videocore6/_version.py"

[tool.setuptools.dynamic]
version = {attr = "_videocore6._version.__version__"} # refer genetated version by setuptools-scm

[tool.uv]
package = true

[dependency-groups]
dev = [
    "matplotlib>=3.10.8",
    "mypy>=1.16.1",
    "pytest>=8.4.1",
    "ruff>=0.12.1",
]

[tool.ruff]
lint.select = [
    "F",  # pyflakes
    "E",  # pycodestyle
    "W",  # pycodestyle warnings
    "I",  # isort
    "D",  # pydocstyle
    "UP", # pyupgrade
    "N",  # pep8-naming
]
lint.ignore = ["F403", "F405", "D203", "D213"]
line-length = 119
exclude = [
    ".venv",
    ".git",
    "__pycache__",
#    "videocore6/_version.py", # generated by setuptools-scm
]

[tool.ruff.lint.pycodestyle]
max-line-length = 119

[tool.ruff.lint.per-file-ignores]
"__init__.py" = ["F401", "D"] # __init__.pyは未使用インポートとドキュメントを無視
"tests/test_*.py" = ["D"] # テストファイルはドキュメントを無視
"examples/*.py" = ["D"] # exampleファイルはドキュメントを無視
"benchmarks/*.py" = ["D"] # benchmarkファイルはドキュメントを無視
"setup.py" = ["D"] # setup.pyはドキュメントを無視

[tool.mypy]
allow_redefinition = true
allow_untyped_globals = false
check_untyped_defs = true
color_output = true
disallow_incomplete_defs = true
disallow_subclassing_any = false
disallow_untyped_calls = false
disallow_untyped_decorators = false
disallow_untyped_defs = true
enable_incomplete_feature = "NewGenericSyntax"
error_summary = true
ignore_missing_imports = true
implicit_reexport = true
namespace_packages = true
no_implicit_optional = true
pretty = true
show_column_numbers = true
show_error_codes = true
show_error_context = true
show_traceback = true
strict = true
warn_no_return = true
warn_redundant_casts = true
warn_return_any = true
warn_unreachable = true
warn_unused_configs = true
warn_unused_ignores = false
